base_url: 
domain: 
res_base_url: resources
#highlighter: pygments
markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot


# course
course_number: CSCI-UA.0002
course_section: "002"
course_section_2: "008"
course_name: Introduction to Computer Programming
course_semester: Spring 2018
course_time: "Tue and Thur, 11:00AM - 12:15PM"
course_time_2: "Tue and Thur, 9:30AM - 10:45PM"
course_room: WWH 312
course_room_2: WWH 202
course_url: http://jvers.com/csci-ua.0002-spring2017-002-008

# office hours
office_hours: "Mon and Tue from 12:30PM to 1:45PM"
office_hours_room: WWH 422

# email
email: "jversoza at cs dot nyu dot edu"

# finals
final_schedule: https://cs.nyu.edu/dynamic/courses/exams/?semester=spring_2018
final_date: Thursday, May 15th
final_time: 10:00AM - 11:50AM
final_room: WWH 312

final_date_2: Thursday, May 10th
final_time_2: 8:00AM - 9:50AM
final_room_2: WWH 202

# books
bookq: Starting Out with Python
bookt: How to Think Like a Computer Scientist

departmental_syllabus: http://cs.nyu.edu/courses/spring18/CSCI-UA.0002-003/common_syllabus/

module1: "http://cs.nyu.edu/elearning/CSCI_UA_0002/module01.php"
module2: "http://cs.nyu.edu/elearning/CSCI_UA_0002/module02.php"
module3: "http://cs.nyu.edu/elearning/CSCI_UA_0002/module03.php"
module4: "http://cs.nyu.edu/elearning/CSCI_UA_0002/module04.php"
module5: "http://cs.nyu.edu/elearning/CSCI_UA_0002/module05.php"
module6: "http://cs.nyu.edu/elearning/CSCI_UA_0002/module06.php"
module7: "http://cs.nyu.edu/elearning/CSCI_UA_0002/module07.php"
module8: "http://cs.nyu.edu/elearning/CSCI_UA_0002/module08.php"
module9: "http://cs.nyu.edu/elearning/CSCI_UA_0002/module09.php"

# manual section change
# http://foureyes.github.io/csci-ua.0002-spring2015-008 -> http://foureyes.github.io/csci-ua.0002-fall2014-010
